global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ml-api'
    static_configs:
      - targets: ['api:8000']
    
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
